# Generated by Django 4.1.4 on 2022-12-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('placejob', models.CharField(max_length=50, null=True)),
                ('usertype', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
