# Generated by Django 4.1.4 on 2023-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0006_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_file', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
