# Generated by Django 4.1.4 on 2023-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0007_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AlterField(
            model_name='alljob',
            name='age',
            field=models.CharField(choices=[('18-24', '18-24'), ('25-35', '25-35'), ('35+', '35+')], max_length=10, null=True),
        ),
    ]
