# Generated by Django 4.1.4 on 2023-01-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0008_delete_job_alter_alljob_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Tech.filemodel'),
        ),
    ]
