# Generated by Django 4.1.4 on 2023-01-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0009_jobseeker_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='file',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='jobseeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Job_Tech.jobseeker'),
        ),
    ]
