# Generated by Django 4.1.4 on 2023-01-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0010_remove_jobseeker_file_filemodel_jobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='user_type',
            field=models.CharField(choices=[('JobSeeker', 'JobSeeker')], max_length=50, null=True),
        ),
    ]
