# Generated by Django 4.1.4 on 2022-12-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReg',
            new_name='UserRe',
        ),
    ]
