# Generated by Django 4.1.4 on 2022-12-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.TextField()),
                ('company', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
