# Generated by Django 4.1.4 on 2022-12-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
