# Generated by Django 4.1.4 on 2022-12-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0002_rename_userreg_userre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRe',
        ),
    ]
