# Generated by Django 4.1.4 on 2022-12-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Tech', '0002_remove_job_user_remove_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserReg',
        ),
    ]
